// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-dVvW2dKCAofzPWaseipazEOfffwvo0w',
    appId: '1:176708850651:web:36e7562abb5dd5dad64dfe',
    messagingSenderId: '176708850651',
    projectId: 'home-service-app-e7698',
    authDomain: 'home-service-app-e7698.firebaseapp.com',
    storageBucket: 'home-service-app-e7698.firebasestorage.app',
    measurementId: 'G-FJ1BC19D0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPaq-qo1OREYvm-3tE6jsTUJ8b1WNHoM',
    appId: '1:176708850651:android:03a60bf6dabd9a09d64dfe',
    messagingSenderId: '176708850651',
    projectId: 'home-service-app-e7698',
    storageBucket: 'home-service-app-e7698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5xRw8v3j5kTtR-eLmrzZwTXWxjNY2NeY',
    appId: '1:176708850651:ios:370b785ff3b8631ed64dfe',
    messagingSenderId: '176708850651',
    projectId: 'home-service-app-e7698',
    storageBucket: 'home-service-app-e7698.firebasestorage.app',
    iosBundleId: 'com.example.homeServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5xRw8v3j5kTtR-eLmrzZwTXWxjNY2NeY',
    appId: '1:176708850651:ios:370b785ff3b8631ed64dfe',
    messagingSenderId: '176708850651',
    projectId: 'home-service-app-e7698',
    storageBucket: 'home-service-app-e7698.firebasestorage.app',
    iosBundleId: 'com.example.homeServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-dVvW2dKCAofzPWaseipazEOfffwvo0w',
    appId: '1:176708850651:web:7d48b200858507fcd64dfe',
    messagingSenderId: '176708850651',
    projectId: 'home-service-app-e7698',
    authDomain: 'home-service-app-e7698.firebaseapp.com',
    storageBucket: 'home-service-app-e7698.firebasestorage.app',
    measurementId: 'G-4DY0V9TPMJ',
  );
}
